const initialState = { search: {
      albums: {
        href: 'https://api.spotify.com/v1/search?query=jewel&type=album&market=AR&offset=0&limit=20',
        items: [
          {
            album_type: 'album',
            artists: [
              {
                external_urls: {
                  spotify: 'https://open.spotify.com/artist/6FbDoZnMBTdhhhLuJBOOqP'
                },
                href: 'https://api.spotify.com/v1/artists/6FbDoZnMBTdhhhLuJBOOqP',
                id: '6FbDoZnMBTdhhhLuJBOOqP',
                name: 'Jewel',
                type: 'artist',
                uri: 'spotify:artist:6FbDoZnMBTdhhhLuJBOOqP'
              }
            ],
            available_markets: [
              'AD',
              'AR',
              'AT',
              'AU',
              'BE',
              'BG',
              'BO',
              'BR',
              'CA',
              'CH',
              'CL',
              'CO',
              'CR',
              'CY',
              'CZ',
              'DE',
              'DK',
              'DO',
              'EC',
              'EE',
              'ES',
              'FI',
              'FR',
              'GB',
              'GR',
              'GT',
              'HK',
              'HN',
              'HU',
              'ID',
              'IE',
              'IS',
              'IT',
              'JP',
              'LI',
              'LT',
              'LU',
              'LV',
              'MC',
              'MT',
              'MX',
              'MY',
              'NI',
              'NL',
              'NO',
              'NZ',
              'PA',
              'PE',
              'PH',
              'PL',
              'PT',
              'PY',
              'SE',
              'SG',
              'SK',
              'SV',
              'TH',
              'TR',
              'TW',
              'US',
              'UY',
              'VN'
            ],
            external_urls: {
              spotify: 'https://open.spotify.com/album/6t0qVXx77kMCVyxHejzJsP'
            },
            href: 'https://api.spotify.com/v1/albums/6t0qVXx77kMCVyxHejzJsP',
            id: '6t0qVXx77kMCVyxHejzJsP',
            images: [
              {
                height: 640,
                url: 'https://i.scdn.co/image/99b16d87ab922aea780c6cf1e0cd80bfca1e354d',
                width: 640
              },
              {
                height: 300,
                url: 'https://i.scdn.co/image/5fc41dcdcd63c1c2a1ca94cf7035033a7bb7707b',
                width: 300
              },
              {
                height: 64,
                url: 'https://i.scdn.co/image/8be6f5b6817887f848045f90b9048fb9c09b2f3f',
                width: 64
              }
            ],
            name: 'Pieces Of You',
            type: 'album',
            uri: 'spotify:album:6t0qVXx77kMCVyxHejzJsP'
          },
          {
            album_type: 'album',
            artists: [
              {
                external_urls: {
                  spotify: 'https://open.spotify.com/artist/4iHNK0tOyZPYnBU7nGAgpQ'
                },
                href: 'https://api.spotify.com/v1/artists/4iHNK0tOyZPYnBU7nGAgpQ',
                id: '4iHNK0tOyZPYnBU7nGAgpQ',
                name: 'Mariah Carey',
                type: 'artist',
                uri: 'spotify:artist:4iHNK0tOyZPYnBU7nGAgpQ'
              }
            ],
            available_markets: [
              'AD',
              'AR',
              'AT',
              'AU',
              'BE',
              'BG',
              'BO',
              'BR',
              'CA',
              'CH',
              'CL',
              'CO',
              'CR',
              'CY',
              'CZ',
              'DE',
              'DK',
              'DO',
              'EC',
              'EE',
              'ES',
              'FI',
              'FR',
              'GB',
              'GR',
              'GT',
              'HK',
              'HN',
              'HU',
              'ID',
              'IE',
              'IS',
              'IT',
              'JP',
              'LI',
              'LT',
              'LU',
              'LV',
              'MC',
              'MT',
              'MX',
              'MY',
              'NI',
              'NL',
              'NO',
              'NZ',
              'PA',
              'PE',
              'PH',
              'PL',
              'PT',
              'PY',
              'SE',
              'SG',
              'SK',
              'SV',
              'TH',
              'TR',
              'TW',
              'US',
              'UY',
              'VN'
            ],
            external_urls: {
              spotify: 'https://open.spotify.com/album/1qmkUjb9IsZgAttODKZPSB'
            },
            href: 'https://api.spotify.com/v1/albums/1qmkUjb9IsZgAttODKZPSB',
            id: '1qmkUjb9IsZgAttODKZPSB',
            images: [
              {
                height: 640,
                url: 'https://i.scdn.co/image/68e86d694e9f984f773d6ff73f692f6064f4b4cd',
                width: 640
              },
              {
                height: 300,
                url: 'https://i.scdn.co/image/2fb7d53aa6431f5c34f1da368dc751cd972f2136',
                width: 300
              },
              {
                height: 64,
                url: 'https://i.scdn.co/image/4469264082a4f5c43a23f1069bad08a97c0b37be',
                width: 64
              }
            ],
            name: 'The Emancipation of Mimi (International Jewel)',
            type: 'album',
            uri: 'spotify:album:1qmkUjb9IsZgAttODKZPSB'
          },
          {
            album_type: 'album',
            artists: [
              {
                external_urls: {
                  spotify: 'https://open.spotify.com/artist/2KofAEA8S0jDDXjSg6a3HR'
                },
                href: 'https://api.spotify.com/v1/artists/2KofAEA8S0jDDXjSg6a3HR',
                id: '2KofAEA8S0jDDXjSg6a3HR',
                name: 'Johnny Jewel',
                type: 'artist',
                uri: 'spotify:artist:2KofAEA8S0jDDXjSg6a3HR'
              }
            ],
            available_markets: [
              'AD',
              'AR',
              'AT',
              'AU',
              'BE',
              'BG',
              'BO',
              'BR',
              'CA',
              'CH',
              'CL',
              'CO',
              'CR',
              'CY',
              'CZ',
              'DE',
              'DK',
              'DO',
              'EC',
              'EE',
              'ES',
              'FI',
              'FR',
              'GB',
              'GR',
              'GT',
              'HK',
              'HN',
              'HU',
              'ID',
              'IE',
              'IS',
              'IT',
              'JP',
              'LI',
              'LT',
              'LU',
              'LV',
              'MC',
              'MT',
              'MX',
              'MY',
              'NI',
              'NL',
              'NO',
              'NZ',
              'PA',
              'PE',
              'PH',
              'PL',
              'PT',
              'PY',
              'SE',
              'SG',
              'SK',
              'SV',
              'TH',
              'TR',
              'TW',
              'US',
              'UY',
              'VN'
            ],
            external_urls: {
              spotify: 'https://open.spotify.com/album/6xGIsWBx6Ub5KA2Wujaxbc'
            },
            href: 'https://api.spotify.com/v1/albums/6xGIsWBx6Ub5KA2Wujaxbc',
            id: '6xGIsWBx6Ub5KA2Wujaxbc',
            images: [
              {
                height: 640,
                url: 'https://i.scdn.co/image/05ee50ebd0d139526a62982faef163330fe6e8b7',
                width: 640
              },
              {
                height: 300,
                url: 'https://i.scdn.co/image/19de65f1b248b10f80e9fb7c84fc6fe0a455edb8',
                width: 300
              },
              {
                height: 64,
                url: 'https://i.scdn.co/image/1ab960188a863c6212339d4191715dfe79e0a617',
                width: 64
              }
            ],
            name: 'Windswept',
            type: 'album',
            uri: 'spotify:album:6xGIsWBx6Ub5KA2Wujaxbc'
          },
          {
            album_type: 'album',
            artists: [
              {
                external_urls: {
                  spotify: 'https://open.spotify.com/artist/6FbDoZnMBTdhhhLuJBOOqP'
                },
                href: 'https://api.spotify.com/v1/artists/6FbDoZnMBTdhhhLuJBOOqP',
                id: '6FbDoZnMBTdhhhLuJBOOqP',
                name: 'Jewel',
                type: 'artist',
                uri: 'spotify:artist:6FbDoZnMBTdhhhLuJBOOqP'
              }
            ],
            available_markets: [
              'AD',
              'AR',
              'AT',
              'AU',
              'BE',
              'BG',
              'BO',
              'BR',
              'CA',
              'CH',
              'CL',
              'CO',
              'CR',
              'CY',
              'CZ',
              'DE',
              'DK',
              'DO',
              'EC',
              'EE',
              'ES',
              'FI',
              'FR',
              'GB',
              'GR',
              'GT',
              'HK',
              'HN',
              'HU',
              'ID',
              'IE',
              'IS',
              'IT',
              'JP',
              'LI',
              'LT',
              'LU',
              'LV',
              'MC',
              'MT',
              'MX',
              'MY',
              'NI',
              'NL',
              'NO',
              'NZ',
              'PA',
              'PE',
              'PH',
              'PL',
              'PT',
              'PY',
              'SE',
              'SG',
              'SK',
              'SV',
              'TH',
              'TR',
              'TW',
              'US',
              'UY',
              'VN'
            ],
            external_urls: {
              spotify: 'https://open.spotify.com/album/6aDRCnCbuqY7NkerfUcyp7'
            },
            href: 'https://api.spotify.com/v1/albums/6aDRCnCbuqY7NkerfUcyp7',
            id: '6aDRCnCbuqY7NkerfUcyp7',
            images: [
              {
                height: 640,
                url: 'https://i.scdn.co/image/e4ff8a8c4efaeeb35f7e652a9d56aff8576feddd',
                width: 640
              },
              {
                height: 300,
                url: 'https://i.scdn.co/image/5df5692d9933ccbdd6152146a1b6cc44f5bb9221',
                width: 300
              },
              {
                height: 64,
                url: 'https://i.scdn.co/image/5bde45380f869f5d128118c249cd0bdd3d116414',
                width: 64
              }
            ],
            name: 'Lullaby',
            type: 'album',
            uri: 'spotify:album:6aDRCnCbuqY7NkerfUcyp7'
          },
          {
            album_type: 'album',
            artists: [
              {
                external_urls: {
                  spotify: 'https://open.spotify.com/artist/6FbDoZnMBTdhhhLuJBOOqP'
                },
                href: 'https://api.spotify.com/v1/artists/6FbDoZnMBTdhhhLuJBOOqP',
                id: '6FbDoZnMBTdhhhLuJBOOqP',
                name: 'Jewel',
                type: 'artist',
                uri: 'spotify:artist:6FbDoZnMBTdhhhLuJBOOqP'
              }
            ],
            available_markets: [
              'AD',
              'AR',
              'AT',
              'AU',
              'BE',
              'BG',
              'BO',
              'BR',
              'CA',
              'CH',
              'CL',
              'CO',
              'CR',
              'CY',
              'CZ',
              'DE',
              'DK',
              'DO',
              'EC',
              'EE',
              'ES',
              'FI',
              'FR',
              'GB',
              'GR',
              'GT',
              'HK',
              'HN',
              'HU',
              'ID',
              'IE',
              'IS',
              'IT',
              'JP',
              'LI',
              'LT',
              'LU',
              'LV',
              'MC',
              'MT',
              'MX',
              'MY',
              'NI',
              'NL',
              'NO',
              'NZ',
              'PA',
              'PE',
              'PH',
              'PL',
              'PT',
              'PY',
              'SE',
              'SG',
              'SK',
              'SV',
              'TH',
              'TR',
              'TW',
              'US',
              'UY',
              'VN'
            ],
            external_urls: {
              spotify: 'https://open.spotify.com/album/66oHhkpwRWqMU0xwwfEFXy'
            },
            href: 'https://api.spotify.com/v1/albums/66oHhkpwRWqMU0xwwfEFXy',
            id: '66oHhkpwRWqMU0xwwfEFXy',
            images: [
              {
                height: 640,
                url: 'https://i.scdn.co/image/da0eec4916f71581158cd707e1ddcbc36c589776',
                width: 640
              },
              {
                height: 300,
                url: 'https://i.scdn.co/image/d6bd669ec4b4c4d12ae40500e8033e88a7c638a6',
                width: 300
              },
              {
                height: 64,
                url: 'https://i.scdn.co/image/32cd81a75d53d8e897b444c465a3684a46cdc7b1',
                width: 64
              }
            ],
            name: 'Spirit',
            type: 'album',
            uri: 'spotify:album:66oHhkpwRWqMU0xwwfEFXy'
          },
          {
            album_type: 'compilation',
            artists: [
              {
                external_urls: {
                  spotify: 'https://open.spotify.com/artist/6FbDoZnMBTdhhhLuJBOOqP'
                },
                href: 'https://api.spotify.com/v1/artists/6FbDoZnMBTdhhhLuJBOOqP',
                id: '6FbDoZnMBTdhhhLuJBOOqP',
                name: 'Jewel',
                type: 'artist',
                uri: 'spotify:artist:6FbDoZnMBTdhhhLuJBOOqP'
              }
            ],
            available_markets: [
              'AD',
              'AR',
              'AT',
              'AU',
              'BE',
              'BG',
              'BO',
              'BR',
              'CA',
              'CH',
              'CL',
              'CO',
              'CR',
              'CY',
              'CZ',
              'DE',
              'DK',
              'DO',
              'EC',
              'EE',
              'ES',
              'FI',
              'FR',
              'GB',
              'GR',
              'GT',
              'HK',
              'HN',
              'HU',
              'ID',
              'IE',
              'IS',
              'IT',
              'JP',
              'LI',
              'LT',
              'LU',
              'LV',
              'MC',
              'MT',
              'MX',
              'MY',
              'NI',
              'NL',
              'NO',
              'NZ',
              'PA',
              'PE',
              'PH',
              'PL',
              'PT',
              'PY',
              'SE',
              'SG',
              'SK',
              'SV',
              'TH',
              'TR',
              'TW',
              'US',
              'UY',
              'VN'
            ],
            external_urls: {
              spotify: 'https://open.spotify.com/album/72ssildvYLP6ZyVg0Jn20m'
            },
            href: 'https://api.spotify.com/v1/albums/72ssildvYLP6ZyVg0Jn20m',
            id: '72ssildvYLP6ZyVg0Jn20m',
            images: [
              {
                height: 640,
                url: 'https://i.scdn.co/image/6582d6d3c747bb6d9100bd18f6e351bea059ec51',
                width: 640
              },
              {
                height: 300,
                url: 'https://i.scdn.co/image/c7c51e513b2d46bb200d1165554d7e9258c4d398',
                width: 300
              },
              {
                height: 64,
                url: 'https://i.scdn.co/image/2aad80690b9f26e92a5f14a5c31df46d584fde48',
                width: 64
              }
            ],
            name: 'The Jewel Collection (JEWEL)',
            type: 'album',
            uri: 'spotify:album:72ssildvYLP6ZyVg0Jn20m'
          },
          {
            album_type: 'single',
            artists: [
              {
                external_urls: {
                  spotify: 'https://open.spotify.com/artist/6FbDoZnMBTdhhhLuJBOOqP'
                },
                href: 'https://api.spotify.com/v1/artists/6FbDoZnMBTdhhhLuJBOOqP',
                id: '6FbDoZnMBTdhhhLuJBOOqP',
                name: 'Jewel',
                type: 'artist',
                uri: 'spotify:artist:6FbDoZnMBTdhhhLuJBOOqP'
              }
            ],
            available_markets: [
              'AD',
              'AR',
              'AT',
              'AU',
              'BE',
              'BG',
              'BO',
              'BR',
              'CA',
              'CH',
              'CL',
              'CO',
              'CR',
              'CY',
              'CZ',
              'DE',
              'DK',
              'DO',
              'EC',
              'EE',
              'ES',
              'FI',
              'FR',
              'GB',
              'GR',
              'GT',
              'HK',
              'HN',
              'HU',
              'ID',
              'IE',
              'IS',
              'IT',
              'JP',
              'LI',
              'LT',
              'LU',
              'LV',
              'MC',
              'MT',
              'MX',
              'MY',
              'NI',
              'NL',
              'NO',
              'NZ',
              'PA',
              'PE',
              'PH',
              'PL',
              'PT',
              'PY',
              'SE',
              'SG',
              'SK',
              'SV',
              'TH',
              'TR',
              'TW',
              'US',
              'UY',
              'VN'
            ],
            external_urls: {
              spotify: 'https://open.spotify.com/album/76GSLXGggAA9EpNQk4VGEo'
            },
            href: 'https://api.spotify.com/v1/albums/76GSLXGggAA9EpNQk4VGEo',
            id: '76GSLXGggAA9EpNQk4VGEo',
            images: [
              {
                height: 640,
                url: 'https://i.scdn.co/image/f7b81e7722b6c3269831812630a85a448c6ad41c',
                width: 640
              },
              {
                height: 300,
                url: 'https://i.scdn.co/image/28e7a7e98c965e07fc826bc9b94055d6c81c3d67',
                width: 300
              },
              {
                height: 64,
                url: 'https://i.scdn.co/image/ac050e4a7151d94e9655ac123d1260185f42a936',
                width: 64
              }
            ],
            name: 'My Sentiment',
            type: 'album',
            uri: 'spotify:album:76GSLXGggAA9EpNQk4VGEo'
          },
          {
            album_type: 'album',
            artists: [
              {
                external_urls: {
                  spotify: 'https://open.spotify.com/artist/6FbDoZnMBTdhhhLuJBOOqP'
                },
                href: 'https://api.spotify.com/v1/artists/6FbDoZnMBTdhhhLuJBOOqP',
                id: '6FbDoZnMBTdhhhLuJBOOqP',
                name: 'Jewel',
                type: 'artist',
                uri: 'spotify:artist:6FbDoZnMBTdhhhLuJBOOqP'
              }
            ],
            available_markets: [
              'AD',
              'AR',
              'AT',
              'AU',
              'BE',
              'BG',
              'BO',
              'BR',
              'CA',
              'CH',
              'CL',
              'CO',
              'CR',
              'CY',
              'CZ',
              'DE',
              'DK',
              'DO',
              'EC',
              'EE',
              'ES',
              'FI',
              'FR',
              'GB',
              'GR',
              'GT',
              'HK',
              'HN',
              'HU',
              'ID',
              'IE',
              'IS',
              'IT',
              'JP',
              'LI',
              'LT',
              'LU',
              'LV',
              'MC',
              'MT',
              'MX',
              'MY',
              'NI',
              'NL',
              'NO',
              'NZ',
              'PA',
              'PE',
              'PH',
              'PL',
              'PT',
              'PY',
              'SE',
              'SG',
              'SK',
              'SV',
              'TH',
              'TR',
              'TW',
              'US',
              'UY',
              'VN'
            ],
            external_urls: {
              spotify: 'https://open.spotify.com/album/2JAeF6QauKwAmVFFc99cMF'
            },
            href: 'https://api.spotify.com/v1/albums/2JAeF6QauKwAmVFFc99cMF',
            id: '2JAeF6QauKwAmVFFc99cMF',
            images: [
              {
                height: 632,
                url: 'https://i.scdn.co/image/ee74a98e5b71ad394fa02e64d37220f9344606d4',
                width: 640
              },
              {
                height: 296,
                url: 'https://i.scdn.co/image/27c8df0fed80a520a65c072cea83c5c3c9255a28',
                width: 300
              },
              {
                height: 63,
                url: 'https://i.scdn.co/image/148307ed58d8f4055f486af003e307a718cbaba6',
                width: 64
              }
            ],
            name: 'This Way',
            type: 'album',
            uri: 'spotify:album:2JAeF6QauKwAmVFFc99cMF'
          },
          {
            album_type: 'compilation',
            artists: [
              {
                external_urls: {
                  spotify: 'https://open.spotify.com/artist/6FbDoZnMBTdhhhLuJBOOqP'
                },
                href: 'https://api.spotify.com/v1/artists/6FbDoZnMBTdhhhLuJBOOqP',
                id: '6FbDoZnMBTdhhhLuJBOOqP',
                name: 'Jewel',
                type: 'artist',
                uri: 'spotify:artist:6FbDoZnMBTdhhhLuJBOOqP'
              }
            ],
            available_markets: [
              'AD',
              'AR',
              'AT',
              'AU',
              'BE',
              'BG',
              'BO',
              'BR',
              'CA',
              'CH',
              'CL',
              'CO',
              'CR',
              'CY',
              'CZ',
              'DE',
              'DK',
              'DO',
              'EC',
              'EE',
              'ES',
              'FI',
              'FR',
              'GB',
              'GR',
              'GT',
              'HK',
              'HN',
              'HU',
              'ID',
              'IE',
              'IS',
              'IT',
              'JP',
              'LI',
              'LT',
              'LU',
              'LV',
              'MC',
              'MT',
              'MX',
              'MY',
              'NI',
              'NL',
              'NO',
              'NZ',
              'PA',
              'PE',
              'PH',
              'PL',
              'PT',
              'PY',
              'SE',
              'SG',
              'SK',
              'SV',
              'TH',
              'TR',
              'TW',
              'US',
              'UY',
              'VN'
            ],
            external_urls: {
              spotify: 'https://open.spotify.com/album/0dgIX61MfnzFdL9mjWYUtf'
            },
            href: 'https://api.spotify.com/v1/albums/0dgIX61MfnzFdL9mjWYUtf',
            id: '0dgIX61MfnzFdL9mjWYUtf',
            images: [
              {
                height: 640,
                url: 'https://i.scdn.co/image/69aa13b634c241d3afe9385bc7a7b45153a55310',
                width: 640
              },
              {
                height: 300,
                url: 'https://i.scdn.co/image/195024ba3907dd7f026be81c338cc26bcbc0af1c',
                width: 300
              },
              {
                height: 64,
                url: 'https://i.scdn.co/image/16586ff099943d0ae23db2c12c8a875e85c96fc6',
                width: 64
              }
            ],
            name: 'Greatest Hits',
            type: 'album',
            uri: 'spotify:album:0dgIX61MfnzFdL9mjWYUtf'
          },
          {
            album_type: 'album',
            artists: [
              {
                external_urls: {
                  spotify: 'https://open.spotify.com/artist/6FbDoZnMBTdhhhLuJBOOqP'
                },
                href: 'https://api.spotify.com/v1/artists/6FbDoZnMBTdhhhLuJBOOqP',
                id: '6FbDoZnMBTdhhhLuJBOOqP',
                name: 'Jewel',
                type: 'artist',
                uri: 'spotify:artist:6FbDoZnMBTdhhhLuJBOOqP'
              }
            ],
            available_markets: [
              'AD',
              'AR',
              'AT',
              'AU',
              'BE',
              'BG',
              'BO',
              'BR',
              'CA',
              'CH',
              'CL',
              'CO',
              'CR',
              'CY',
              'CZ',
              'DE',
              'DK',
              'DO',
              'EC',
              'EE',
              'ES',
              'FI',
              'FR',
              'GB',
              'GR',
              'GT',
              'HK',
              'HN',
              'HU',
              'ID',
              'IE',
              'IS',
              'IT',
              'JP',
              'LI',
              'LT',
              'LU',
              'LV',
              'MC',
              'MT',
              'MX',
              'MY',
              'NI',
              'NL',
              'NO',
              'NZ',
              'PA',
              'PE',
              'PH',
              'PL',
              'PT',
              'PY',
              'SE',
              'SG',
              'SK',
              'SV',
              'TH',
              'TR',
              'TW',
              'US',
              'UY',
              'VN'
            ],
            external_urls: {
              spotify: 'https://open.spotify.com/album/2uXmASzvhIl8hQJvVKh8ij'
            },
            href: 'https://api.spotify.com/v1/albums/2uXmASzvhIl8hQJvVKh8ij',
            id: '2uXmASzvhIl8hQJvVKh8ij',
            images: [
              {
                height: 640,
                url: 'https://i.scdn.co/image/b361d5285497350e7addae73c29b7cb0c984596c',
                width: 640
              },
              {
                height: 300,
                url: 'https://i.scdn.co/image/4380c93946ae1f880fc6263d8e067d27ffe8b277',
                width: 300
              },
              {
                height: 64,
                url: 'https://i.scdn.co/image/5e85cdef17fdb3415ca5a4425512a5e512632743',
                width: 64
              }
            ],
            name: 'Picking Up The Pieces',
            type: 'album',
            uri: 'spotify:album:2uXmASzvhIl8hQJvVKh8ij'
          },
          {
            album_type: 'album',
            artists: [
              {
                external_urls: {
                  spotify: 'https://open.spotify.com/artist/3sjtmLaxBX2uQypDRE3IlN'
                },
                href: 'https://api.spotify.com/v1/artists/3sjtmLaxBX2uQypDRE3IlN',
                id: '3sjtmLaxBX2uQypDRE3IlN',
                name: 'Nite Jewel',
                type: 'artist',
                uri: 'spotify:artist:3sjtmLaxBX2uQypDRE3IlN'
              }
            ],
            available_markets: [
              'AD',
              'AR',
              'AT',
              'AU',
              'BE',
              'BG',
              'BO',
              'BR',
              'CA',
              'CH',
              'CL',
              'CO',
              'CR',
              'CY',
              'CZ',
              'DE',
              'DK',
              'DO',
              'EC',
              'EE',
              'ES',
              'FI',
              'FR',
              'GB',
              'GR',
              'GT',
              'HK',
              'HN',
              'HU',
              'ID',
              'IE',
              'IS',
              'IT',
              'JP',
              'LI',
              'LT',
              'LU',
              'LV',
              'MC',
              'MT',
              'MX',
              'MY',
              'NI',
              'NL',
              'NO',
              'NZ',
              'PA',
              'PE',
              'PH',
              'PL',
              'PT',
              'PY',
              'SE',
              'SG',
              'SK',
              'SV',
              'TH',
              'TR',
              'TW',
              'US',
              'UY',
              'VN'
            ],
            external_urls: {
              spotify: 'https://open.spotify.com/album/2XonesGr0YvUdhmdCW102B'
            },
            href: 'https://api.spotify.com/v1/albums/2XonesGr0YvUdhmdCW102B',
            id: '2XonesGr0YvUdhmdCW102B',
            images: [
              {
                height: 640,
                url: 'https://i.scdn.co/image/282c68db12d805fa00d975affc0f152e0ba64696',
                width: 640
              },
              {
                height: 300,
                url: 'https://i.scdn.co/image/55dde3a3f7a4d0a526664f5f9fd7c28f85dcbc8c',
                width: 300
              },
              {
                height: 64,
                url: 'https://i.scdn.co/image/8eee60e0569c45aca1989a7fc98a8c6f683ff9e0',
                width: 64
              }
            ],
            name: 'Real High',
            type: 'album',
            uri: 'spotify:album:2XonesGr0YvUdhmdCW102B'
          },
          {
            album_type: 'album',
            artists: [
              {
                external_urls: {
                  spotify: 'https://open.spotify.com/artist/2KofAEA8S0jDDXjSg6a3HR'
                },
                href: 'https://api.spotify.com/v1/artists/2KofAEA8S0jDDXjSg6a3HR',
                id: '2KofAEA8S0jDDXjSg6a3HR',
                name: 'Johnny Jewel',
                type: 'artist',
                uri: 'spotify:artist:2KofAEA8S0jDDXjSg6a3HR'
              }
            ],
            available_markets: [
              'AD',
              'AR',
              'AT',
              'AU',
              'BE',
              'BG',
              'BO',
              'BR',
              'CA',
              'CH',
              'CL',
              'CO',
              'CR',
              'CY',
              'CZ',
              'DE',
              'DK',
              'DO',
              'EC',
              'EE',
              'ES',
              'FI',
              'FR',
              'GB',
              'GR',
              'GT',
              'HK',
              'HN',
              'HU',
              'ID',
              'IE',
              'IS',
              'IT',
              'JP',
              'LI',
              'LT',
              'LU',
              'LV',
              'MC',
              'MT',
              'MX',
              'MY',
              'NI',
              'NL',
              'NO',
              'NZ',
              'PA',
              'PE',
              'PH',
              'PL',
              'PT',
              'PY',
              'SE',
              'SG',
              'SK',
              'SV',
              'TH',
              'TR',
              'TW',
              'US',
              'UY',
              'VN'
            ],
            external_urls: {
              spotify: 'https://open.spotify.com/album/1fdu93lqV9HkLAjXTbrDxi'
            },
            href: 'https://api.spotify.com/v1/albums/1fdu93lqV9HkLAjXTbrDxi',
            id: '1fdu93lqV9HkLAjXTbrDxi',
            images: [
              {
                height: 640,
                url: 'https://i.scdn.co/image/f3c31b8f513061b0dfe1dcdc9b0985329190ab00',
                width: 640
              },
              {
                height: 300,
                url: 'https://i.scdn.co/image/13d0fb0fcfc0f5708ab1839cd5f186a60cfc84cc',
                width: 300
              },
              {
                height: 64,
                url: 'https://i.scdn.co/image/87a590b6144e95374a0b474e0c5e20f6dc28668c',
                width: 64
              }
            ],
            name: 'Music To Drive',
            type: 'album',
            uri: 'spotify:album:1fdu93lqV9HkLAjXTbrDxi'
          },
          {
            album_type: 'album',
            artists: [
              {
                external_urls: {
                  spotify: 'https://open.spotify.com/artist/37zKpwMQ7NFzk0MPR4FUJe'
                },
                href: 'https://api.spotify.com/v1/artists/37zKpwMQ7NFzk0MPR4FUJe',
                id: '37zKpwMQ7NFzk0MPR4FUJe',
                name: 'Marcella Detroit',
                type: 'artist',
                uri: 'spotify:artist:37zKpwMQ7NFzk0MPR4FUJe'
              }
            ],
            available_markets: [
              'AD',
              'AR',
              'AT',
              'AU',
              'BE',
              'BG',
              'BO',
              'BR',
              'CA',
              'CH',
              'CL',
              'CO',
              'CR',
              'CY',
              'CZ',
              'DE',
              'DK',
              'DO',
              'EC',
              'EE',
              'ES',
              'FI',
              'FR',
              'GB',
              'GR',
              'GT',
              'HK',
              'HN',
              'HU',
              'ID',
              'IE',
              'IS',
              'IT',
              'JP',
              'LI',
              'LT',
              'LU',
              'LV',
              'MC',
              'MT',
              'MX',
              'MY',
              'NI',
              'NL',
              'NO',
              'NZ',
              'PA',
              'PE',
              'PH',
              'PL',
              'PT',
              'PY',
              'SE',
              'SG',
              'SK',
              'SV',
              'TH',
              'TR',
              'TW',
              'US',
              'UY',
              'VN'
            ],
            external_urls: {
              spotify: 'https://open.spotify.com/album/54ZWytpe2LLcDeSGQNXiPu'
            },
            href: 'https://api.spotify.com/v1/albums/54ZWytpe2LLcDeSGQNXiPu',
            id: '54ZWytpe2LLcDeSGQNXiPu',
            images: [
              {
                height: 636,
                url: 'https://i.scdn.co/image/5ceb793f7034cc792e3be36c4b22ea556a987033',
                width: 640
              },
              {
                height: 298,
                url: 'https://i.scdn.co/image/66792e4b2276c58666cf7a979c019ab0658ce48d',
                width: 300
              },
              {
                height: 64,
                url: 'https://i.scdn.co/image/711fef3ccdf44b9f6f1f95fdf0a33fca885e0ce1',
                width: 64
              }
            ],
            name: 'Jewel',
            type: 'album',
            uri: 'spotify:album:54ZWytpe2LLcDeSGQNXiPu'
          },
          {
            album_type: 'album',
            artists: [
              {
                external_urls: {
                  spotify: 'https://open.spotify.com/artist/72f733zGuCPEzCSLs9wOVi'
                },
                href: 'https://api.spotify.com/v1/artists/72f733zGuCPEzCSLs9wOVi',
                id: '72f733zGuCPEzCSLs9wOVi',
                name: 'Adriana Calcanhotto',
                type: 'artist',
                uri: 'spotify:artist:72f733zGuCPEzCSLs9wOVi'
              }
            ],
            available_markets: [
              'AD',
              'AR',
              'AT',
              'AU',
              'BE',
              'BG',
              'BO',
              'BR',
              'CA',
              'CH',
              'CL',
              'CO',
              'CR',
              'CY',
              'CZ',
              'DE',
              'DK',
              'DO',
              'EC',
              'EE',
              'ES',
              'FI',
              'FR',
              'GB',
              'GR',
              'GT',
              'HK',
              'HN',
              'HU',
              'ID',
              'IE',
              'IS',
              'IT',
              'JP',
              'LI',
              'LT',
              'LU',
              'LV',
              'MC',
              'MT',
              'MX',
              'MY',
              'NI',
              'NL',
              'NO',
              'NZ',
              'PA',
              'PE',
              'PH',
              'PL',
              'PT',
              'PY',
              'SE',
              'SG',
              'SK',
              'SV',
              'TH',
              'TR',
              'TW',
              'US',
              'UY',
              'VN'
            ],
            external_urls: {
              spotify: 'https://open.spotify.com/album/0ybpx0wxg13NQfJkDFVad4'
            },
            href: 'https://api.spotify.com/v1/albums/0ybpx0wxg13NQfJkDFVad4',
            id: '0ybpx0wxg13NQfJkDFVad4',
            images: [
              {
                height: 576,
                url: 'https://i.scdn.co/image/23e1fba00f485eca9e97e65f038caee986979323',
                width: 640
              },
              {
                height: 270,
                url: 'https://i.scdn.co/image/c6829ed9b3cf5581cd86a50c903bc854bb144f98',
                width: 300
              },
              {
                height: 58,
                url: 'https://i.scdn.co/image/ec93b3eecb902468aadee198ca372c69d8801398',
                width: 64
              }
            ],
            name: 'O Micróbio do Samba (Jewel Case Version)',
            type: 'album',
            uri: 'spotify:album:0ybpx0wxg13NQfJkDFVad4'
          },
          {
            album_type: 'album',
            artists: [
              {
                external_urls: {
                  spotify: 'https://open.spotify.com/artist/1PfOXooPSLQhOTNZGrXM90'
                },
                href: 'https://api.spotify.com/v1/artists/1PfOXooPSLQhOTNZGrXM90',
                id: '1PfOXooPSLQhOTNZGrXM90',
                name: 'Solarstone',
                type: 'artist',
                uri: 'spotify:artist:1PfOXooPSLQhOTNZGrXM90'
              },
              {
                external_urls: {
                  spotify: 'https://open.spotify.com/artist/4zdJthk33AZlEot0q8FMoM'
                },
                href: 'https://api.spotify.com/v1/artists/4zdJthk33AZlEot0q8FMoM',
                id: '4zdJthk33AZlEot0q8FMoM',
                name: 'Clare Stagg',
                type: 'artist',
                uri: 'spotify:artist:4zdJthk33AZlEot0q8FMoM'
              }
            ],
            available_markets: [
              'AD',
              'AR',
              'AT',
              'AU',
              'BE',
              'BG',
              'BO',
              'BR',
              'CA',
              'CH',
              'CL',
              'CO',
              'CR',
              'CY',
              'CZ',
              'DE',
              'DK',
              'DO',
              'EC',
              'EE',
              'ES',
              'FI',
              'FR',
              'GB',
              'GR',
              'GT',
              'HK',
              'HN',
              'HU',
              'ID',
              'IE',
              'IS',
              'IT',
              'JP',
              'LI',
              'LT',
              'LU',
              'LV',
              'MC',
              'MT',
              'MX',
              'MY',
              'NI',
              'NL',
              'NO',
              'NZ',
              'PA',
              'PE',
              'PH',
              'PL',
              'PT',
              'PY',
              'SE',
              'SG',
              'SK',
              'SV',
              'TH',
              'TR',
              'TW',
              'US',
              'UY',
              'VN'
            ],
            external_urls: {
              spotify: 'https://open.spotify.com/album/0oCNo4xu7tly1P1FPlaMxO'
            },
            href: 'https://api.spotify.com/v1/albums/0oCNo4xu7tly1P1FPlaMxO',
            id: '0oCNo4xu7tly1P1FPlaMxO',
            images: [
              {
                height: 640,
                url: 'https://i.scdn.co/image/c1c391a8fd64bf1cad19a53d072304b3f00bae33',
                width: 640
              },
              {
                height: 300,
                url: 'https://i.scdn.co/image/bc73508366e67efb70966b3b0f9bb0d9d60933ff',
                width: 300
              },
              {
                height: 64,
                url: 'https://i.scdn.co/image/771db1fe0968118ccd71c1e3b0fdb2989f974850',
                width: 64
              }
            ],
            name: 'Jewel',
            type: 'album',
            uri: 'spotify:album:0oCNo4xu7tly1P1FPlaMxO'
          },
          {
            album_type: 'album',
            artists: [
              {
                external_urls: {
                  spotify: 'https://open.spotify.com/artist/1t10zmdWTK7n4nIJWThPMt'
                },
                href: 'https://api.spotify.com/v1/artists/1t10zmdWTK7n4nIJWThPMt',
                id: '1t10zmdWTK7n4nIJWThPMt',
                name: 'Dechen Shak-Dagsay',
                type: 'artist',
                uri: 'spotify:artist:1t10zmdWTK7n4nIJWThPMt'
              }
            ],
            available_markets: [
              'AD',
              'AR',
              'AT',
              'AU',
              'BE',
              'BG',
              'BO',
              'BR',
              'CA',
              'CH',
              'CL',
              'CO',
              'CR',
              'CY',
              'CZ',
              'DE',
              'DK',
              'DO',
              'EC',
              'EE',
              'ES',
              'FI',
              'FR',
              'GB',
              'GR',
              'GT',
              'HK',
              'HN',
              'HU',
              'ID',
              'IE',
              'IS',
              'IT',
              'JP',
              'LI',
              'LT',
              'LU',
              'LV',
              'MC',
              'MT',
              'MX',
              'MY',
              'NI',
              'NL',
              'NO',
              'NZ',
              'PA',
              'PE',
              'PH',
              'PL',
              'PT',
              'PY',
              'SE',
              'SG',
              'SK',
              'SV',
              'TH',
              'TR',
              'TW',
              'US',
              'UY',
              'VN'
            ],
            external_urls: {
              spotify: 'https://open.spotify.com/album/4L8s5HxDxtSarKm4pVDu7x'
            },
            href: 'https://api.spotify.com/v1/albums/4L8s5HxDxtSarKm4pVDu7x',
            id: '4L8s5HxDxtSarKm4pVDu7x',
            images: [
              {
                height: 640,
                url: 'https://i.scdn.co/image/02d1d9c9151716e7e1fc40aa777702df49fde1d4',
                width: 640
              },
              {
                height: 300,
                url: 'https://i.scdn.co/image/1b4ce72eac9b1e9ceb4424191c5b36757a421bc2',
                width: 300
              },
              {
                height: 64,
                url: 'https://i.scdn.co/image/f48fac781a509c7615eced82e9c31a94f0c02a06',
                width: 64
              }
            ],
            name: 'Jewel',
            type: 'album',
            uri: 'spotify:album:4L8s5HxDxtSarKm4pVDu7x'
          },
          {
            album_type: 'album',
            artists: [
              {
                external_urls: {
                  spotify: 'https://open.spotify.com/artist/6FbDoZnMBTdhhhLuJBOOqP'
                },
                href: 'https://api.spotify.com/v1/artists/6FbDoZnMBTdhhhLuJBOOqP',
                id: '6FbDoZnMBTdhhhLuJBOOqP',
                name: 'Jewel',
                type: 'artist',
                uri: 'spotify:artist:6FbDoZnMBTdhhhLuJBOOqP'
              }
            ],
            available_markets: [
              'AD',
              'AR',
              'AT',
              'AU',
              'BE',
              'BG',
              'BO',
              'BR',
              'CA',
              'CH',
              'CL',
              'CO',
              'CR',
              'CY',
              'CZ',
              'DE',
              'DK',
              'DO',
              'EC',
              'EE',
              'ES',
              'FI',
              'FR',
              'GB',
              'GR',
              'GT',
              'HK',
              'HN',
              'HU',
              'ID',
              'IE',
              'IS',
              'IT',
              'JP',
              'LI',
              'LT',
              'LU',
              'LV',
              'MC',
              'MT',
              'MX',
              'MY',
              'NI',
              'NL',
              'NO',
              'NZ',
              'PA',
              'PE',
              'PH',
              'PL',
              'PT',
              'PY',
              'SE',
              'SG',
              'SK',
              'SV',
              'TH',
              'TR',
              'TW',
              'US',
              'UY',
              'VN'
            ],
            external_urls: {
              spotify: 'https://open.spotify.com/album/7gj1Py9ZW7q7C1VNMWg5yB'
            },
            href: 'https://api.spotify.com/v1/albums/7gj1Py9ZW7q7C1VNMWg5yB',
            id: '7gj1Py9ZW7q7C1VNMWg5yB',
            images: [
              {
                height: 640,
                url: 'https://i.scdn.co/image/97ce681808f5fb30ac0052f97f1b72258d81e35e',
                width: 640
              },
              {
                height: 300,
                url: 'https://i.scdn.co/image/9970d1d1b0aecb917199d4b65045166b8a7c67af',
                width: 300
              },
              {
                height: 64,
                url: 'https://i.scdn.co/image/8516021d808c814a90306238cc5e6b6152857c0a',
                width: 64
              }
            ],
            name: 'Sweet And Wild',
            type: 'album',
            uri: 'spotify:album:7gj1Py9ZW7q7C1VNMWg5yB'
          },
          {
            album_type: 'album',
            artists: [
              {
                external_urls: {
                  spotify: 'https://open.spotify.com/artist/6FbDoZnMBTdhhhLuJBOOqP'
                },
                href: 'https://api.spotify.com/v1/artists/6FbDoZnMBTdhhhLuJBOOqP',
                id: '6FbDoZnMBTdhhhLuJBOOqP',
                name: 'Jewel',
                type: 'artist',
                uri: 'spotify:artist:6FbDoZnMBTdhhhLuJBOOqP'
              }
            ],
            available_markets: [
              'AD',
              'AR',
              'AT',
              'AU',
              'BE',
              'BG',
              'BO',
              'BR',
              'CA',
              'CH',
              'CL',
              'CO',
              'CR',
              'CY',
              'CZ',
              'DE',
              'DK',
              'DO',
              'EC',
              'EE',
              'ES',
              'FI',
              'FR',
              'GB',
              'GR',
              'GT',
              'HK',
              'HN',
              'HU',
              'ID',
              'IE',
              'IS',
              'IT',
              'JP',
              'LI',
              'LT',
              'LU',
              'LV',
              'MC',
              'MT',
              'MX',
              'MY',
              'NI',
              'NL',
              'NO',
              'NZ',
              'PA',
              'PE',
              'PH',
              'PL',
              'PT',
              'PY',
              'SE',
              'SG',
              'SK',
              'SV',
              'TH',
              'TR',
              'TW',
              'US',
              'UY',
              'VN'
            ],
            external_urls: {
              spotify: 'https://open.spotify.com/album/08FbvOYc6W5fGgr3EjVFyA'
            },
            href: 'https://api.spotify.com/v1/albums/08FbvOYc6W5fGgr3EjVFyA',
            id: '08FbvOYc6W5fGgr3EjVFyA',
            images: [
              {
                height: 640,
                url: 'https://i.scdn.co/image/5369d43c544add129a403fd217d9b3c664d7ec30',
                width: 640
              },
              {
                height: 300,
                url: 'https://i.scdn.co/image/ecf868e76aa81339af77cfb7487c013bc492e302',
                width: 300
              },
              {
                height: 64,
                url: 'https://i.scdn.co/image/cf4d2995df73fbcca1d573474bece7855a88a4c8',
                width: 64
              }
            ],
            name: 'Sweet And Wild',
            type: 'album',
            uri: 'spotify:album:08FbvOYc6W5fGgr3EjVFyA'
          },
          {
            album_type: 'album',
            artists: [
              {
                external_urls: {
                  spotify: 'https://open.spotify.com/artist/6FbDoZnMBTdhhhLuJBOOqP'
                },
                href: 'https://api.spotify.com/v1/artists/6FbDoZnMBTdhhhLuJBOOqP',
                id: '6FbDoZnMBTdhhhLuJBOOqP',
                name: 'Jewel',
                type: 'artist',
                uri: 'spotify:artist:6FbDoZnMBTdhhhLuJBOOqP'
              }
            ],
            available_markets: [
              'AD',
              'AR',
              'AT',
              'AU',
              'BE',
              'BG',
              'BO',
              'BR',
              'CA',
              'CH',
              'CL',
              'CO',
              'CR',
              'CY',
              'CZ',
              'DE',
              'DK',
              'DO',
              'EC',
              'EE',
              'ES',
              'FI',
              'FR',
              'GB',
              'GR',
              'GT',
              'HK',
              'HN',
              'HU',
              'ID',
              'IE',
              'IS',
              'IT',
              'JP',
              'LI',
              'LT',
              'LU',
              'LV',
              'MC',
              'MT',
              'MX',
              'MY',
              'NI',
              'NL',
              'NO',
              'NZ',
              'PA',
              'PE',
              'PH',
              'PL',
              'PT',
              'PY',
              'SE',
              'SG',
              'SK',
              'SV',
              'TH',
              'TR',
              'TW',
              'US',
              'UY',
              'VN'
            ],
            external_urls: {
              spotify: 'https://open.spotify.com/album/6AIQBilP1zUAkgOQMLTGOv'
            },
            href: 'https://api.spotify.com/v1/albums/6AIQBilP1zUAkgOQMLTGOv',
            id: '6AIQBilP1zUAkgOQMLTGOv',
            images: [
              {
                height: 640,
                url: 'https://i.scdn.co/image/52ec9fa399d3db0b10dc3609a0269f3fb4a474b1',
                width: 640
              },
              {
                height: 300,
                url: 'https://i.scdn.co/image/cfdadac05c8dc19cf86321b4bdbb37f0c7a7dcc5',
                width: 300
              },
              {
                height: 64,
                url: 'https://i.scdn.co/image/f4e0158697e21ce92179e135c93d207111f0f3f0',
                width: 64
              }
            ],
            name: '0304 (European Version- alternate enhancement)',
            type: 'album',
            uri: 'spotify:album:6AIQBilP1zUAkgOQMLTGOv'
          },
          {
            album_type: 'album',
            artists: [
              {
                external_urls: {
                  spotify: 'https://open.spotify.com/artist/3sjtmLaxBX2uQypDRE3IlN'
                },
                href: 'https://api.spotify.com/v1/artists/3sjtmLaxBX2uQypDRE3IlN',
                id: '3sjtmLaxBX2uQypDRE3IlN',
                name: 'Nite Jewel',
                type: 'artist',
                uri: 'spotify:artist:3sjtmLaxBX2uQypDRE3IlN'
              }
            ],
            available_markets: [
              'AD',
              'AR',
              'AT',
              'AU',
              'BE',
              'BG',
              'BO',
              'BR',
              'CA',
              'CH',
              'CL',
              'CO',
              'CR',
              'CY',
              'CZ',
              'DE',
              'DK',
              'DO',
              'EC',
              'EE',
              'ES',
              'FI',
              'FR',
              'GB',
              'GR',
              'GT',
              'HK',
              'HN',
              'HU',
              'ID',
              'IE',
              'IS',
              'IT',
              'JP',
              'LI',
              'LT',
              'LU',
              'LV',
              'MC',
              'MT',
              'MX',
              'MY',
              'NI',
              'NL',
              'NO',
              'NZ',
              'PA',
              'PE',
              'PH',
              'PL',
              'PT',
              'PY',
              'SE',
              'SG',
              'SK',
              'SV',
              'TH',
              'TR',
              'TW',
              'US',
              'UY',
              'VN'
            ],
            external_urls: {
              spotify: 'https://open.spotify.com/album/7hkC66iggqfMBbsJE8dE0F'
            },
            href: 'https://api.spotify.com/v1/albums/7hkC66iggqfMBbsJE8dE0F',
            id: '7hkC66iggqfMBbsJE8dE0F',
            images: [
              {
                height: 640,
                url: 'https://i.scdn.co/image/ed49d584f8f1ec6a7e09e0a669a67f34d182b71f',
                width: 640
              },
              {
                height: 300,
                url: 'https://i.scdn.co/image/24c5e085545b3621d69f2f5774a1fbf5e0981cb4',
                width: 300
              },
              {
                height: 64,
                url: 'https://i.scdn.co/image/c920eece82ce4612d848348a6f380d399835d5c2',
                width: 64
              }
            ],
            name: 'Liquid Cool',
            type: 'album',
            uri: 'spotify:album:7hkC66iggqfMBbsJE8dE0F'
          }
        ],
        limit: 20,
        next: 'https://api.spotify.com/v1/search?query=jewel&type=album&market=AR&offset=20&limit=20',
        offset: 0,
        previous: null,
        total: 672
      }
    },
    user: {
        auth_token: 'BQAC7BcXsHuD0NOsPsV-v9nZ4X8bM9hXAK3qms_jInEY--KqhV3sJyZoL6Wh-rtgH1slPI2EJMb-tNAcKqCQFyjcXDwu48xl-sRdh3Hl3ezEkugEU1MNBHmwYV04exnEpC_JlxsqDqEbKYy9GZh3GcNuc0w',
        refresh_token: 'AQDjQGOrER87JE3gyyA-bU0NtPwx-xAQc0brGfhVERrB1mQWlYyBAVbOCmTrGOAfcySy1fpqPUsr2pIKT-sOArO7D-Xk0FK6ZuOu55NK_1Q89kkSiP3ERj5QR2D3srhUIBk',
        expiration: '3600'
      },
      router: {
        location: {
          pathname: '/',
          search: '',
          hash: '',
          key: 'gead64'
        }
      }
    }

export default initialState    